// <auto-generated>
// Gerado por scripts\\build_macro.ps1 a partir de src\\*.cs. Nao edite diretamente.
// </auto-generated>

#pragma warning disable 1633 // Unrecognized #pragma directive
#pragma reference "Tekla.Macros.Runtime"
#pragma reference "Tekla.Macros.Akit"
#pragma warning restore 1633 // Unrecognized #pragma directive

using System;
using System.Collections;
using System.Collections.Generic;
using System.Drawing;
using System.Text;
using System.Windows.Forms;
using Tekla.Structures;
using Tekla.Structures.Model;
using Tekla.Structures.Geometry3d;
using Tekla.Structures.Filtering;
using Tekla.Structures.Filtering.Categories;
using ModelUI = Tekla.Structures.Model.UI;


public class Script
{
    [Tekla.Macros.Runtime.MacroEntryPointAttribute()]
    public static void Run(Tekla.Macros.Runtime.IMacroRuntime runtime)
    {
        MenuUi.Show(runtime);
    }
}


internal static class MenuUi
{
    // --- Paleta de Cores (Design System) ---
    private static readonly Color C_FundoForm = Color.FromArgb(240, 242, 245);
    private static readonly Color C_CardFundo = Color.White;
    private static readonly Color C_Cabecalho = Color.FromArgb(0, 80, 150);
    private static readonly Color C_TextoPrimario = Color.FromArgb(30, 30, 30);
    private static readonly Color C_TextoSecundario = Color.FromArgb(100, 110, 120);
    private static readonly Color C_TextoClaro = Color.White;
    private static readonly Color C_TextoCabecalhoSec = Color.FromArgb(200, 220, 255);
    private static readonly Color C_Borda = Color.FromArgb(220, 224, 230);
    private static readonly Color C_Transparente = Color.Transparent;

    // Cores de Acao
    private static readonly Color C_BotaoHover = Color.FromArgb(245, 248, 255);
    private static readonly Color C_DestaqueAzul = Color.FromArgb(0, 120, 215);
    private static readonly Color C_DestaqueVermelho = Color.FromArgb(220, 53, 69);
    private static readonly Color C_FundoVermelhoSuave = Color.FromArgb(255, 245, 245);
    private static readonly Color C_FundoVermelhoHover = Color.FromArgb(255, 230, 230);

    // Tipografia
    private static readonly Font F_Titulo = new Font("Segoe UI", 12F, FontStyle.Bold);
    private static readonly Font F_Texto = new Font("Segoe UI", 10F, FontStyle.Regular);
    private static readonly Font F_Secao = new Font("Segoe UI", 10F, FontStyle.Bold);

    public static void Show(Tekla.Macros.Runtime.IMacroRuntime runtime)
    {
        using (var form = new Form())
        {
            // 1. Configuracoes da Janela
            form.Text = "MarnaTeklaOS - Painel de Controle";
            form.StartPosition = FormStartPosition.CenterScreen;
            form.Size = new Size(480, 600);
            form.MinimumSize = new Size(440, 520);
            form.Font = F_Texto;
            form.BackColor = C_FundoForm;
            form.FormBorderStyle = FormBorderStyle.FixedSingle;
            form.MaximizeBox = false;
            form.TopMost = true;

            var mainLayout = new TableLayoutPanel();
            mainLayout.Dock = DockStyle.Fill;
            mainLayout.ColumnCount = 1;
            mainLayout.RowCount = 3;
            mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 92F));
            mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));

            // 2. Cabecalho (Header)
            var headerPanel = new Panel();
            headerPanel.Dock = DockStyle.Fill;
            headerPanel.BackColor = C_Cabecalho;
            headerPanel.Padding = new Padding(16, 12, 16, 12);

            var headerTextLayout = new TableLayoutPanel();
            headerTextLayout.Dock = DockStyle.Fill;
            headerTextLayout.ColumnCount = 1;
            headerTextLayout.RowCount = 2;
            headerTextLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            headerTextLayout.RowStyles.Add(new RowStyle(SizeType.AutoSize));

            var lblTitle = new Label();
            lblTitle.Text = "MarnaTeklaOS";
            lblTitle.ForeColor = C_TextoClaro;
            lblTitle.Font = F_Titulo;
            lblTitle.AutoSize = true;
            lblTitle.Dock = DockStyle.Fill;

            var lblSub = new Label();
            lblSub.Text = "Utilitarios para Tekla Structures";
            lblSub.ForeColor = C_TextoCabecalhoSec;
            lblSub.Font = F_Texto;
            lblSub.AutoSize = true;
            lblSub.Dock = DockStyle.Fill;

            headerTextLayout.Controls.Add(lblTitle, 0, 0);
            headerTextLayout.Controls.Add(lblSub, 0, 1);
            headerPanel.Controls.Add(headerTextLayout);

            // 3. Dashboard de Conteudo
            var contentPanel = new Panel();
            contentPanel.Dock = DockStyle.Fill;
            contentPanel.Padding = new Padding(16);
            contentPanel.AutoScroll = true;

            var dashboardLayout = new TableLayoutPanel();
            dashboardLayout.Dock = DockStyle.Top;
            dashboardLayout.AutoSize = true;
            dashboardLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            dashboardLayout.ColumnCount = 1;
            dashboardLayout.RowCount = 0;
            dashboardLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            contentPanel.SizeChanged += (s, e) =>
            {
                dashboardLayout.Width = Math.Max(0, contentPanel.ClientSize.Width - contentPanel.Padding.Horizontal);
            };
            dashboardLayout.Width = Math.Max(0, contentPanel.ClientSize.Width - contentPanel.Padding.Horizontal);

            var grpReports = CriarGrupoDashboard("Relatorios e consultas");
            var reportsLayout = CriarLayoutVertical();

            var btnGeral = CriarBotaoDashboard("Gerar relatorio do modelo", false);
            btnGeral.Click += delegate {
                string r = ReportBuilder.BuildReport();
                if(!string.IsNullOrEmpty(r)) ReportWindow.ShowReport(r);
            };

            var btnSel = CriarBotaoDashboard("Ver pecas selecionadas", false);
            btnSel.Click += delegate {
                string r = ReportBuilder.BuildSelectedPartsReport();
                if(!string.IsNullOrEmpty(r)) ReportWindow.ShowReport(r);
            };

            AdicionarLinha(reportsLayout, btnGeral);
            AdicionarLinha(reportsLayout, btnSel);
            grpReports.Controls.Add(reportsLayout);
            AdicionarLinha(dashboardLayout, grpReports);

            var grpSelection = CriarGrupoDashboard("Selecao de pecas");
            var selectionLayout = CriarLayoutVertical();

            var txtSelectionInput = new TextBox();
            txtSelectionInput.Dock = DockStyle.Fill;
            txtSelectionInput.Height = 30;
            txtSelectionInput.Font = F_Texto;
            txtSelectionInput.Margin = new Padding(0, 0, 0, 8);
            txtSelectionInput.BackColor = C_CardFundo;

var btnSelectParts = CriarBotaoDashboard("Selecionar pecas", false);
btnSelectParts.MinimumSize = new Size(200, 36);
            btnSelectParts.Click += delegate {
                AssemblySelectionHelper.SelectAssemblies(txtSelectionInput.Text);
            };

            var selectionTooltip = new ToolTip();
            selectionTooltip.SetToolTip(btnSelectParts, "Digite os nomes dos conjuntos separados por virgula (ex.: PP1,PP2,VR1).");

            var selectionActions = new FlowLayoutPanel();
            selectionActions.FlowDirection = FlowDirection.LeftToRight;
            selectionActions.AutoSize = true;
            selectionActions.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            selectionActions.Dock = DockStyle.Top;
            selectionActions.Padding = new Padding(0);
            selectionActions.Margin = new Padding(0, 0, 0, 16);
            selectionActions.WrapContents = false;

            var btnSelectionHelp = new Button();
            btnSelectionHelp.Text = "[?]";
            btnSelectionHelp.Height = 36;
            btnSelectionHelp.Width = 36;
            btnSelectionHelp.FlatStyle = FlatStyle.Flat;
            btnSelectionHelp.FlatAppearance.BorderSize = 1;
            btnSelectionHelp.FlatAppearance.BorderColor = C_Borda;
            btnSelectionHelp.BackColor = C_CardFundo;
            btnSelectionHelp.ForeColor = C_DestaqueAzul;
            btnSelectionHelp.Font = F_Texto;
            btnSelectionHelp.Cursor = Cursors.Hand;
            btnSelectionHelp.Margin = new Padding(6, 0, 0, 0);
            btnSelectionHelp.Click += delegate {
                MessageBox.Show(
                    "Digite os nomes dos conjuntos separados por virgula (ex.: PP1,PP2,VR1).",
                    "Como usar",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information
                );
            };

            selectionActions.Controls.Add(btnSelectParts);
            selectionActions.Controls.Add(btnSelectionHelp);

            AdicionarLinha(selectionLayout, txtSelectionInput);
            AdicionarLinha(selectionLayout, selectionActions);
            grpSelection.Controls.Add(selectionLayout);
            AdicionarLinha(dashboardLayout, grpSelection);

            var grpActions = CriarGrupoDashboard("Acoes do modelo");
            var actionsLayout = CriarLayoutVertical();

            var btnRepair = CriarBotaoDashboard("Diagnosticar e reparar modelo", true);
            btnRepair.Click += delegate { TeklaCommands.RunModelRepair(runtime); };
            btnRepair.MinimumSize = new Size(200, 36);

            var repairTooltip = new ToolTip();
            repairTooltip.SetToolTip(btnRepair, "Use esta opcao caso o modelo apresente lentidao ou erros de numeracao.");

            var repairActions = new FlowLayoutPanel();
            repairActions.FlowDirection = FlowDirection.LeftToRight;
            repairActions.AutoSize = true;
            repairActions.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            repairActions.Dock = DockStyle.Top;
            repairActions.Padding = new Padding(0);
            repairActions.Margin = new Padding(0, 0, 0, 16);
            repairActions.WrapContents = false;

            var btnRepairHelp = new Button();
            btnRepairHelp.Text = "[?]";
            btnRepairHelp.Height = 36;
            btnRepairHelp.Width = 36;
            btnRepairHelp.FlatStyle = FlatStyle.Flat;
            btnRepairHelp.FlatAppearance.BorderSize = 1;
            btnRepairHelp.FlatAppearance.BorderColor = C_Borda;
            btnRepairHelp.BackColor = C_CardFundo;
            btnRepairHelp.ForeColor = C_DestaqueAzul;
            btnRepairHelp.Font = F_Texto;
            btnRepairHelp.Cursor = Cursors.Hand;
            btnRepairHelp.Margin = new Padding(6, 0, 0, 0);
            btnRepairHelp.Click += delegate {
                MessageBox.Show(
                    "Use esta opcao caso o modelo apresente lentidao ou erros de numeracao.",
                    "Como usar",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information
                );
            };

            repairActions.Controls.Add(btnRepair);
            repairActions.Controls.Add(btnRepairHelp);

            AdicionarLinha(actionsLayout, repairActions);

            var btnCompare = CriarBotaoDashboard("Comparar conjuntos", false);
            btnCompare.Click += delegate { AssemblyComparator.CompareSelectedAssemblies(); };

            var compareTooltip = new ToolTip();
            compareTooltip.SetToolTip(btnCompare, "Selecione exatamente dois conjuntos (ex: PP1 e PP2) e clique para comparar as pecas lado a lado.");

            AdicionarLinha(actionsLayout, btnCompare);
            grpActions.Controls.Add(actionsLayout);
            AdicionarLinha(dashboardLayout, grpActions);

            contentPanel.Controls.Add(dashboardLayout);

            // 4. Rodape
            var footerPanel = new Panel();
            footerPanel.Dock = DockStyle.Fill;
            footerPanel.BackColor = C_CardFundo;
            footerPanel.Padding = new Padding(16, 8, 16, 8);

            var chkTransp = new CheckBox();
            chkTransp.Text = "Modo Transparente";
            chkTransp.AutoSize = true;
            chkTransp.Cursor = Cursors.Hand;
            chkTransp.Dock = DockStyle.Left;
            chkTransp.ForeColor = C_TextoSecundario;
            chkTransp.BackColor = C_CardFundo;
            chkTransp.Font = F_Texto;
            chkTransp.CheckedChanged += delegate { form.Opacity = chkTransp.Checked ? 0.85 : 1.0; };

            var btnClose = new Button();
            btnClose.Text = "Fechar";
            btnClose.AutoSize = false;
            btnClose.Size = new Size(90, 30);
            btnClose.Dock = DockStyle.Right;
            btnClose.FlatStyle = FlatStyle.Flat;
            btnClose.FlatAppearance.BorderSize = 1;
            btnClose.FlatAppearance.BorderColor = C_Borda;
            btnClose.BackColor = C_CardFundo;
            btnClose.Cursor = Cursors.Hand;
            btnClose.ForeColor = C_TextoPrimario;
            btnClose.Font = F_Texto;
            btnClose.DialogResult = DialogResult.OK;

            footerPanel.Controls.Add(chkTransp);
            footerPanel.Controls.Add(btnClose);

            mainLayout.Controls.Add(headerPanel, 0, 0);
            mainLayout.Controls.Add(contentPanel, 0, 1);
            mainLayout.Controls.Add(footerPanel, 0, 2);
            form.Controls.Add(mainLayout);
            form.AcceptButton = btnClose;
            form.CancelButton = btnClose;

            form.ShowDialog();
        }
    }

    // --- Helpers UI ---
    private static GroupBox CriarGrupoDashboard(string titulo)
    {
        var group = new GroupBox();
        group.Text = titulo;
        group.Font = F_Secao;
        group.ForeColor = C_TextoPrimario;
        group.BackColor = C_CardFundo;
        group.Dock = DockStyle.Top;
        group.AutoSize = true;
        group.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        group.Padding = new Padding(12, 8, 12, 12);
        group.Margin = new Padding(0, 0, 0, 12);
        return group;
    }

    private static TableLayoutPanel CriarLayoutVertical()
    {
        var layout = new TableLayoutPanel();
        layout.ColumnCount = 1;
        layout.RowCount = 0;
        layout.Dock = DockStyle.Top;
        layout.AutoSize = true;
        layout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        layout.Margin = new Padding(0);
        layout.Padding = new Padding(0);
        layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        return layout;
    }

    private static void AdicionarLinha(TableLayoutPanel layout, Control control)
    {
        if (layout == null || control == null)
        {
            return;
        }

        int row = layout.RowCount;
        layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout.Controls.Add(control, 0, row);
        layout.RowCount = row + 1;
    }

    private static Label CriarLabelInfo(string texto)
    {
        var label = new Label();
        label.Text = texto;
        label.ForeColor = C_TextoSecundario;
        label.Font = F_Texto;
        label.AutoSize = true;
        label.Dock = DockStyle.Fill;
        label.Margin = new Padding(0, 0, 0, 8);
        return label;
    }

    private static Button CriarBotaoDashboard(string texto, bool ehPerigo)
    {
        var btn = new Button();
        btn.Text = texto;
        btn.Height = 36;
        btn.Dock = DockStyle.Fill;
        btn.FlatStyle = FlatStyle.Flat;
        btn.FlatAppearance.BorderSize = 1;
        btn.FlatAppearance.BorderColor = C_Borda;
        btn.Cursor = Cursors.Hand;
        btn.Font = F_Texto;
        btn.TextAlign = ContentAlignment.MiddleLeft;
        btn.Padding = new Padding(12, 0, 12, 0);
        btn.Margin = new Padding(0, 0, 0, 8);
        btn.BackColor = ehPerigo ? C_FundoVermelhoSuave : C_CardFundo;
        btn.ForeColor = ehPerigo ? C_DestaqueVermelho : C_TextoPrimario;

        btn.MouseEnter += (s, e) => {
            btn.BackColor = ehPerigo ? C_FundoVermelhoHover : C_BotaoHover;
            if (!ehPerigo) btn.ForeColor = C_DestaqueAzul;
        };

        btn.MouseLeave += (s, e) => {
            btn.BackColor = ehPerigo ? C_FundoVermelhoSuave : C_CardFundo;
            btn.ForeColor = ehPerigo ? C_DestaqueVermelho : C_TextoPrimario;
        };
        return btn;
    }

}



internal static class ReportBuilder
{
    public static string BuildReport()
    {
        var model = new Model();
        if (!model.GetConnectionStatus())
        {
            MessageBox.Show("Relatorio do Modelo\n\nNao foi possivel conectar ao modelo Tekla. Abra um modelo e tente novamente.");
            return null;
        }

        var info = model.GetInfo();
        var projectInfo = model.GetProjectInfo();

        var sb = new StringBuilder();
        sb.AppendLine("Relatorio do Modelo");
        sb.AppendLine();
        sb.AppendLine("Modelo");
        sb.AppendLine(string.Format("Nome: {0}", Formatters.FormatValue(info.ModelName)));
        sb.AppendLine(string.Format("Caminho: {0}", Formatters.FormatValue(info.ModelPath)));
        sb.AppendLine(string.Format("Fase atual: {0}", info.CurrentPhase));
        sb.AppendLine(string.Format("Modelo compartilhado: {0}", Formatters.FormatBool(info.SharedModel)));
        sb.AppendLine(string.Format("Modelo single user: {0}", Formatters.FormatBool(info.SingleUserModel)));
        sb.AppendLine(string.Format("North direction: {0}", Formatters.FormatValue(info.NorthDirection)));
        sb.AppendLine();
        sb.AppendLine("Projeto");
        if (projectInfo == null)
        {
            sb.AppendLine("Nao foi possivel obter ProjectInfo.");
        }
        else
        {
            sb.AppendLine(string.Format("Nome: {0}", Formatters.FormatValue(projectInfo.Name)));
            sb.AppendLine(string.Format("Numero: {0}", Formatters.FormatValue(projectInfo.ProjectNumber)));
            sb.AppendLine(string.Format("Descricao: {0}", Formatters.FormatValue(projectInfo.Description)));
            sb.AppendLine(string.Format("Inicio: {0}", Formatters.FormatDate(projectInfo.StartDate)));
            sb.AppendLine(string.Format("Termino: {0}", Formatters.FormatDate(projectInfo.EndDate)));
            sb.AppendLine(string.Format("Designer: {0}", Formatters.FormatValue(projectInfo.Designer)));
            sb.AppendLine(string.Format("Objeto: {0}", Formatters.FormatValue(projectInfo.Object)));
            sb.AppendLine(string.Format("Localizacao: {0}", Formatters.FormatValue(projectInfo.Location)));
            sb.AppendLine(string.Format("Endereco: {0}", Formatters.FormatValue(projectInfo.Address)));
            sb.AppendLine(string.Format("Caixa postal: {0}", Formatters.FormatValue(projectInfo.PostalBox)));
            sb.AppendLine(string.Format("Cidade: {0}", Formatters.FormatValue(projectInfo.Town)));
            sb.AppendLine(string.Format("Regiao: {0}", Formatters.FormatValue(projectInfo.Region)));
            sb.AppendLine(string.Format("CEP: {0}", Formatters.FormatValue(projectInfo.PostalCode)));
            sb.AppendLine(string.Format("Pais: {0}", Formatters.FormatValue(projectInfo.Country)));
            sb.AppendLine(string.Format("Construtora: {0}", Formatters.FormatValue(projectInfo.Builder)));
            sb.AppendLine(string.Format("Info1: {0}", Formatters.FormatValue(projectInfo.Info1)));
            sb.AppendLine(string.Format("Info2: {0}", Formatters.FormatValue(projectInfo.Info2)));
            sb.AppendLine(string.Format("GUID: {0}", Formatters.FormatValue(projectInfo.GUID)));
        }

        return sb.ToString();
    }

    public static string BuildSelectedPartsReport()
    {
        var model = new Model();
        if (!model.GetConnectionStatus())
        {
            MessageBox.Show("Relatorio do Modelo\n\nNao foi possivel conectar ao modelo Tekla. Abra um modelo e tente novamente.");
            return null;
        }

        var selector = new ModelUI.ModelObjectSelector();
        var selected = selector.GetSelectedObjects();
        if (selected == null)
        {
            MessageBox.Show("Nenhum objeto selecionado.");
            return null;
        }

        var details = new StringBuilder();
        int totalSelected = 0;
        int partsCount = 0;

        while (selected.MoveNext())
        {
            totalSelected++;
            var part = selected.Current as Part;
            if (part == null)
            {
                continue;
            }

            partsCount++;
            details.AppendLine(string.Format("Peca {0}", partsCount));
            details.AppendLine(string.Format("Tipo: {0}", Formatters.FormatValue(part.GetType().Name)));
            details.AppendLine(string.Format("Nome: {0}", Formatters.FormatValue(part.Name)));
            details.AppendLine(string.Format("Perfil: {0}", Formatters.FormatValue(part.Profile == null ? null : part.Profile.ProfileString)));
            details.AppendLine(string.Format("Material: {0}", Formatters.FormatValue(part.Material == null ? null : part.Material.MaterialString)));
            details.AppendLine(string.Format("Classe: {0}", Formatters.FormatValue(part.Class)));
            details.AppendLine(string.Format("Acabamento: {0}", Formatters.FormatValue(part.Finish)));
            details.AppendLine(string.Format("Fase: {0}", Formatters.FormatPhaseNumber(part)));
            details.AppendLine(string.Format("GUID: {0}", Formatters.FormatValue(part.Identifier == null ? null : part.Identifier.GUID.ToString())));
            details.AppendLine();
        }

        if (totalSelected == 0)
        {
            MessageBox.Show("Nenhum objeto selecionado.");
            return null;
        }

        if (partsCount == 0)
        {
            MessageBox.Show("Nao ha pecas selecionadas. Selecione pecas e tente novamente.");
            return null;
        }

        var sb = new StringBuilder();
        sb.AppendLine("Pecas selecionadas");
        sb.AppendLine(string.Format("Total de objetos selecionados: {0}", totalSelected));
        sb.AppendLine(string.Format("Total de pecas: {0}", partsCount));
        sb.AppendLine();
        sb.Append(details.ToString());

        return sb.ToString();
    }
}


internal static class ReportWindow
{
    public static void ShowReport(string text)
    {
        using (var form = new Form())
        using (var textBox = new RichTextBox())
        using (var copyButton = new Button())
        using (var closeButton = new Button())
        using (var panel = new TableLayoutPanel())
        using (var buttonPanel = new FlowLayoutPanel())
        {
            form.Text = "Informacoes do Modelo";
            form.StartPosition = FormStartPosition.CenterScreen;
            form.Size = new Size(720, 520);
            form.MinimumSize = new Size(540, 360);

            textBox.Multiline = true;
            textBox.ReadOnly = true;
            textBox.ScrollBars = RichTextBoxScrollBars.Both;
            textBox.WordWrap = false;
            textBox.Dock = DockStyle.Fill;
            textBox.Font = new Font("Consolas", 9f);
            textBox.BackColor = SystemColors.Window;
            textBox.ForeColor = SystemColors.WindowText;
            textBox.Clear();
            AppendColoredText(textBox, text);

            copyButton.Text = "Copiar";
            copyButton.AutoSize = true;
            copyButton.Click += delegate { Clipboard.SetText(textBox.Text); };

            closeButton.Text = "Fechar";
            closeButton.AutoSize = true;
            closeButton.DialogResult = DialogResult.OK;

            buttonPanel.FlowDirection = FlowDirection.RightToLeft;
            buttonPanel.Dock = DockStyle.Fill;
            buttonPanel.AutoSize = true;
            buttonPanel.Controls.Add(closeButton);
            buttonPanel.Controls.Add(copyButton);

            panel.Dock = DockStyle.Fill;
            panel.ColumnCount = 1;
            panel.RowCount = 2;
            panel.RowStyles.Add(new RowStyle(SizeType.Percent, 100f));
            panel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            panel.Controls.Add(textBox, 0, 0);
            panel.Controls.Add(buttonPanel, 0, 1);

            form.Controls.Add(panel);
            form.AcceptButton = closeButton;
            form.CancelButton = closeButton;

            form.ShowDialog();
        }
    }

    private static void AppendColoredText(RichTextBox box, string text)
    {
        if (string.IsNullOrEmpty(text))
        {
            return;
        }

        string normalized = text.Replace("\r\n", "\n");
        string[] lines = normalized.Split('\n');
        for (int i = 0; i < lines.Length; i++)
        {
            string line = lines[i];
            Color color = SystemColors.WindowText;

            if (line.StartsWith("[OK]"))
            {
                color = Color.ForestGreen;
            }
            else if (line.StartsWith("[X]"))
            {
                color = Color.Firebrick;
            }

            box.SelectionStart = box.TextLength;
            box.SelectionLength = 0;
            box.SelectionColor = color;
            box.AppendText(line);
            if (i < lines.Length - 1)
            {
                box.AppendText(Environment.NewLine);
            }
        }

        box.SelectionColor = box.ForeColor;
    }
}


internal static class TeklaCommands
{
    public static void RunModelRepair(Tekla.Macros.Runtime.IMacroRuntime runtime)
    {
        if (runtime == null)
        {
            MessageBox.Show("Nao foi possivel acessar o runtime da macro.");
            return;
        }

        Tekla.Macros.Akit.IAkitScriptHost akit = runtime.Get<Tekla.Macros.Akit.IAkitScriptHost>();
        if (akit == null)
        {
            MessageBox.Show("Nao foi possivel acessar o Akit.");
            return;
        }

        akit.Callback("acmd_check_database", "1", "main_frame");
        // Repara o banco de dados de bibliotecas (xslib) apos o reparo do modelo.
        akit.Callback("acmd_check_database", "XS_LIB_CORRECT", "main_frame");
    }
}


internal static class Formatters
{
    public static string FormatValue(string value)
    {
        return string.IsNullOrEmpty(value) ? "-" : value;
    }

    public static string FormatValue(object value)
    {
        return value == null ? "-" : value.ToString();
    }

    public static string FormatBool(bool value)
    {
        return value ? "Sim" : "Nao";
    }

    public static string FormatPhaseNumber(ModelObject modelObject)
    {
        if (modelObject == null)
        {
            return "-";
        }

        Phase phase;
        if (modelObject.GetPhase(out phase))
        {
            return phase.PhaseNumber.ToString();
        }

        return "-";
    }

    public static string FormatDate(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return "-";
        }

        DateTime parsed;
        if (DateTime.TryParse(value, out parsed))
        {
            return parsed.ToString("yyyy-MM-dd");
        }

        return value;
    }
}


internal static class AssemblySelectionHelper
{
    private static readonly StringComparer Comparer = StringComparer.OrdinalIgnoreCase;

    public static void SelectAssemblies(string input)
    {
        if (string.IsNullOrWhiteSpace(input))
        {
            MessageBox.Show("Informe ao menos um nome de conjunto.");
            return;
        }

        var model = new Model();
        if (!model.GetConnectionStatus())
        {
            MessageBox.Show("Nao foi possivel conectar ao modelo. Abra um modelo e tente novamente.");
            return;
        }

        var tokens = input.Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
        var requestedMapping = new System.Collections.Generic.Dictionary<string, string>(Comparer);
        var requestedOrder = new System.Collections.Generic.List<string>();

        foreach (var token in tokens)
        {
            var trimmed = token.Trim();
            var normalized = NormalizeKey(trimmed);
            if (normalized == null || requestedMapping.ContainsKey(normalized))
            {
                continue;
            }

            requestedMapping[normalized] = trimmed;
            requestedOrder.Add(normalized);
        }

        if (requestedMapping.Count == 0)
        {
            MessageBox.Show("Informe ao menos um nome de conjunto.");
            return;
        }

        var selection = new System.Collections.ArrayList();
        var selectionIds = new System.Collections.Generic.HashSet<long>();
        var foundNames = new System.Collections.Generic.HashSet<string>(Comparer);

        TrySelectAssembliesByFilters(model, requestedOrder, selection, selectionIds, foundNames);

        var missingNormalized = new System.Collections.Generic.HashSet<string>(Comparer);
        foreach (var normalized in requestedMapping.Keys)
        {
            if (!foundNames.Contains(normalized))
            {
                missingNormalized.Add(normalized);
            }
        }

        if (missingNormalized.Count > 0)
        {
            var enumerator = model.GetModelObjectSelector().GetAllObjectsWithType(ModelObject.ModelObjectEnum.ASSEMBLY);
            if (enumerator == null)
            {
                MessageBox.Show("Nao foi possivel obter os conjuntos do modelo.");
                return;
            }

            var previousCursor = Cursor.Current;
            Cursor.Current = Cursors.WaitCursor;
            try
            {
                int processed = 0;
                while (enumerator.MoveNext())
                {
                    processed++;
                    if (processed % 200 == 0)
                    {
                        Application.DoEvents();
                    }

                    var assembly = enumerator.Current as Assembly;
                    if (assembly == null)
                    {
                        continue;
                    }

                    foreach (var candidate in GetNormalizedAssemblyKeys(assembly))
                    {
                        if (!missingNormalized.Contains(candidate))
                        {
                            continue;
                        }

                        AddAssemblyToSelection(selection, selectionIds, assembly);
                        foundNames.Add(candidate);
                        missingNormalized.Remove(candidate);
                        break;
                    }

                    if (missingNormalized.Count == 0)
                    {
                        break;
                    }
                }
            }
            finally
            {
                Cursor.Current = previousCursor;
            }
        }

        if (selection.Count == 0)
        {
            MessageBox.Show("Nenhum conjunto encontrado com os nomes informados.");
            return;
        }

        var selector = new ModelUI.ModelObjectSelector();
        selector.Select(selection, false);

        if (foundNames.Count < requestedMapping.Count)
        {
            var missingBuilder = new StringBuilder();
            foreach (var normalized in requestedOrder)
            {
                if (foundNames.Contains(normalized))
                {
                    continue;
                }

                if (missingBuilder.Length > 0)
                {
                    missingBuilder.Append(", ");
                }

                missingBuilder.Append(requestedMapping[normalized]);
            }

            MessageBox.Show("Nao foram encontrados os seguintes conjuntos: " + missingBuilder.ToString());
        }
    }

    private static System.Collections.Generic.IEnumerable<string> GetNormalizedAssemblyKeys(Assembly assembly)
    {
        var seen = new System.Collections.Generic.HashSet<string>(Comparer);

        foreach (var candidate in GetAssemblyCandidateValues(assembly))
        {
            var normalized = NormalizeKey(candidate);
            if (normalized != null && seen.Add(normalized))
            {
                yield return normalized;
            }
        }
    }

    private static System.Collections.Generic.IEnumerable<string> GetAssemblyCandidateValues(Assembly assembly)
    {
        if (!string.IsNullOrWhiteSpace(assembly.Name))
        {
            yield return assembly.Name;
        }

        var number = assembly.AssemblyNumber;
        if (number != null)
        {
            var numberString = number.ToString();
            if (!string.IsNullOrWhiteSpace(numberString))
            {
                yield return numberString;
            }
        }

        var identifier = assembly.Identifier;
        if (identifier != null)
        {
            yield return identifier.ID.ToString();
        }

        foreach (var reportValue in TryGetReportValues(assembly))
        {
            yield return reportValue;
        }
    }

    private static System.Collections.Generic.IEnumerable<string> TryGetReportValues(Assembly assembly)
    {
        foreach (var propertyName in new[] { "POSITION", "ASSEMBLY_POSITION", "ASSEMBLY_POS", "POSITION_NAME", "ASSEMBLY_NUMBER", "POSITION_ID" })
        {
            var reportValue = TryGetReportProperty(assembly, propertyName);
            if (!string.IsNullOrWhiteSpace(reportValue))
            {
                yield return reportValue;
            }
        }
    }

    private static string TryGetReportProperty(Assembly assembly, string propertyName)
    {
        try
        {
            string stringValue = null;
            if (assembly.GetReportProperty(propertyName, ref stringValue) && !string.IsNullOrWhiteSpace(stringValue))
            {
                return stringValue;
            }

            double doubleValue = 0;
            if (assembly.GetReportProperty(propertyName, ref doubleValue))
            {
                return doubleValue.ToString();
            }

            int intValue = 0;
            if (assembly.GetReportProperty(propertyName, ref intValue))
            {
                return intValue.ToString();
            }

            return null;
        }
        catch
        {
            return null;
        }
    }

    private static string NormalizeKey(string input)
    {
        if (string.IsNullOrWhiteSpace(input))
        {
            return null;
        }

        var trimmed = input.Trim();
        return trimmed.Length == 0 ? null : trimmed;
    }

    private static readonly Func<string, BinaryFilterExpressionCollection>[] AssemblyFilterFactories =
        new Func<string, BinaryFilterExpressionCollection>[]
        {
            value => BuildAssemblyStringFilter(() => new AssemblyFilterExpressions.Name(), value),
            value => BuildAssemblyStringFilter(() => new AssemblyFilterExpressions.PositionNumber(), value)
        };

    private static void TrySelectAssembliesByFilters(Model model, System.Collections.Generic.IEnumerable<string> normalizedKeys, System.Collections.ArrayList selection, System.Collections.Generic.HashSet<long> selectionIds, System.Collections.Generic.HashSet<string> foundNames)
    {
        if (model == null || normalizedKeys == null)
        {
            return;
        }

        var selector = model.GetModelObjectSelector();
        if (selector == null)
        {
            return;
        }

        foreach (var normalized in normalizedKeys)
        {
            if (string.IsNullOrWhiteSpace(normalized) || foundNames.Contains(normalized))
            {
                continue;
            }

            if (TryGatherAssembliesByFilter(selector, normalized, selection, selectionIds))
            {
                foundNames.Add(normalized);
            }
        }
    }

    private static bool TryGatherAssembliesByFilter(ModelObjectSelector selector, string normalized, System.Collections.ArrayList selection, System.Collections.Generic.HashSet<long> selectionIds)
    {
        foreach (var factory in AssemblyFilterFactories)
        {
            var filter = factory(normalized);
            if (filter == null)
            {
                continue;
            }

            var enumerator = selector.GetObjectsByFilter(filter);
            if (enumerator == null)
            {
                continue;
            }

            var found = false;
            while (enumerator.MoveNext())
            {
                var assembly = enumerator.Current as Assembly;
                if (assembly == null)
                {
                    continue;
                }

                AddAssemblyToSelection(selection, selectionIds, assembly);
                found = true;
            }

            if (found)
            {
                return true;
            }
        }

        return false;
    }

    private static void AddAssemblyToSelection(System.Collections.ArrayList selection, System.Collections.Generic.HashSet<long> selectionIds, Assembly assembly)
    {
        if (assembly == null)
        {
            return;
        }

        var identifier = assembly.Identifier;
        if (identifier != null && identifier.ID != 0)
        {
            if (selectionIds.Add(identifier.ID))
            {
                selection.Add(assembly);
            }

            return;
        }

        if (!selection.Contains(assembly))
        {
            selection.Add(assembly);
        }
    }

    private static BinaryFilterExpressionCollection BuildAssemblyStringFilter(Func<StringFilterExpression> propertyFactory, string normalized)
    {
        if (propertyFactory == null || string.IsNullOrWhiteSpace(normalized))
        {
            return null;
        }

        var propertyExpression = propertyFactory();
        if (propertyExpression == null)
        {
            return null;
        }

        var collection = new BinaryFilterExpressionCollection();

        var typeFilter = new BinaryFilterExpression(
            new ObjectFilterExpressions.Type(),
            NumericOperatorType.IS_EQUAL,
            new NumericConstantFilterExpression((int)TeklaStructuresDatabaseTypeEnum.ASSEMBLY));
        collection.Add(new BinaryFilterExpressionItem(typeFilter, BinaryFilterOperatorType.BOOLEAN_AND));

        var stringFilter = new BinaryFilterExpression(
            propertyExpression,
            StringOperatorType.IS_EQUAL,
            new StringConstantFilterExpression(normalized));
        collection.Add(new BinaryFilterExpressionItem(stringFilter, BinaryFilterOperatorType.BOOLEAN_AND));

        return collection;
    }
}


internal static class AssemblyComparator
{
    private const bool IncludeOkDetails = true;

    public static void CompareSelectedAssemblies()
    {
        Model model = new Model();
        if (!model.GetConnectionStatus())
        {
            MessageBox.Show("Nao foi possivel conectar ao modelo Tekla. Abra um modelo e tente novamente.");
            return;
        }

        ModelUI.ModelObjectSelector uiSelector = new ModelUI.ModelObjectSelector();
        ModelObjectEnumerator enumSelected = uiSelector.GetSelectedObjects();
        if (enumSelected == null)
        {
            MessageBox.Show("Nenhum objeto selecionado.");
            return;
        }

        ArrayList assemblies = new ArrayList();
        while (enumSelected.MoveNext())
        {
            Assembly ass = enumSelected.Current as Assembly;
            if (ass != null)
            {
                assemblies.Add(ass);
            }
        }

        if (assemblies.Count != 2)
        {
            MessageBox.Show("Selecione exatamente dois conjuntos para comparar.");
            return;
        }

        Assembly ass1 = (Assembly)assemblies[0];
        Assembly ass2 = (Assembly)assemblies[1];

        StringBuilder sb = new StringBuilder();
        AppendAssemblyComparison(sb, ass1, ass2, model);

        ReportWindow.ShowReport(sb.ToString());
    }

    private static void AppendAssemblyComparison(StringBuilder sb, Assembly ass1, Assembly ass2, Model model)
    {
        sb.AppendLine("RESULTADO COMPARADOR (NUMERACAO)");
        sb.AppendLine("Conjunto 1: " + Formatters.FormatValue(ass1.Name));
        sb.AppendLine("Conjunto 2: " + Formatters.FormatValue(ass2.Name));
        sb.AppendLine();

        sb.AppendLine("SERIE DE NUMERACAO:");
        bool seriesEqual = AppendNumberingSeriesComparison(sb, ass1, ass2);
        sb.AppendLine();

        if (!seriesEqual)
        {
            sb.AppendLine("Comparacao interrompida: series diferentes.");
            sb.AppendLine();
            return;
        }

        sb.AppendLine("PECA PRINCIPAL:");
        AppendMainPartComparison(sb, ass1, ass2);
        sb.AppendLine();

        sb.AppendLine("SECUNDARIAS:");
        AppendSecondariesComparison(sb, ass1, ass2, model);
        sb.AppendLine();

        sb.AppendLine("PROPRIEDADES DO CONJUNTO:");
        AppendAssemblyPropertiesComparison(sb, ass1, ass2);
        sb.AppendLine();
    }

    private static bool AppendNumberingSeriesComparison(StringBuilder sb, Assembly ass1, Assembly ass2)
    {
        string prefix1 = GetAssemblyNumberPrefix(ass1);
        string prefix2 = GetAssemblyNumberPrefix(ass2);
        string start1 = GetAssemblyNumberStart(ass1);
        string start2 = GetAssemblyNumberStart(ass2);

        int okCount = 0;
        int diffCount = 0;

        if (AppendCompareLine(sb, "Prefixo", prefix1, prefix2))
        {
            okCount++;
        }
        else
        {
            diffCount++;
        }

        if (AppendCompareLine(sb, "StartNumber", start1, start2))
        {
            okCount++;
        }
        else
        {
            diffCount++;
        }

        AppendSectionSummary(sb, okCount, diffCount);

        return diffCount == 0;
    }

    private static void AppendMainPartComparison(StringBuilder sb, Assembly ass1, Assembly ass2)
    {
        Part main1 = ass1.GetMainPart() as Part;
        Part main2 = ass2.GetMainPart() as Part;

        if (main1 == null || main2 == null)
        {
            sb.AppendLine("[X] Peca principal: nao encontrada em um dos conjuntos.");
            return;
        }

        int okCount = 0;
        int diffCount = 0;

        if (AppendCompareLine(sb, "Perfil", GetReportProperty(main1, "PROFILE"), GetReportProperty(main2, "PROFILE")))
        {
            okCount++;
        }
        else
        {
            diffCount++;
        }

        if (AppendCompareLine(sb, "Material", GetReportProperty(main1, "MATERIAL"), GetReportProperty(main2, "MATERIAL")))
        {
            okCount++;
        }
        else
        {
            diffCount++;
        }

        if (AppendCompareLine(sb, "Acabamento", GetPartFinish(main1), GetPartFinish(main2)))
        {
            okCount++;
        }
        else
        {
            diffCount++;
        }

        if (AppendCompareLine(sb, "Deformacao", GetReportProperty(main1, "DEFORMATION"), GetReportProperty(main2, "DEFORMATION")))
        {
            okCount++;
        }
        else
        {
            diffCount++;
        }

        if (AppendCompareLine(sb, "Nome (config)", GetPartName(main1), GetPartName(main2)))
        {
            okCount++;
        }
        else
        {
            diffCount++;
        }

        if (AppendCompareLine(sb, "Classe (info)", GetPartClass(main1), GetPartClass(main2)))
        {
            okCount++;
        }
        else
        {
            diffCount++;
        }

        AppendSectionSummary(sb, okCount, diffCount);
    }

    private static void AppendSecondariesComparison(StringBuilder sb, Assembly ass1, Assembly ass2, Model model)
    {
        int count1;
        int count2;
        Dictionary<string, int> map1 = BuildSecondarySignatureCounts(ass1, model, out count1);
        Dictionary<string, int> map2 = BuildSecondarySignatureCounts(ass2, model, out count2);

        int okCount = 0;
        int diffCount = 0;

        if (AppendCompareLine(sb, "Quantidade", count1, count2))
        {
            okCount++;
        }
        else
        {
            diffCount++;
        }

        List<string> diffLines = BuildSecondaryDiffLines(map1, map2);
        bool geomOk = diffLines.Count == 0;
        if (AppendStatusLine(sb, "Geometria/posicao relativa", geomOk))
        {
            okCount++;
        }
        else
        {
            diffCount++;
        }

        if (diffLines.Count > 0)
        {
            foreach (string line in diffLines)
            {
                sb.AppendLine(line);
            }
        }

        AppendSectionSummary(sb, okCount, diffCount);
    }

    private static Dictionary<string, int> BuildSecondarySignatureCounts(Assembly ass, Model model, out int count)
    {
        Dictionary<string, int> map = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
        count = 0;

        if (ass == null || model == null)
        {
            return map;
        }

        Part main = ass.GetMainPart() as Part;

        WorkPlaneHandler handler = model.GetWorkPlaneHandler();
        TransformationPlane originalPlane = handler.GetCurrentTransformationPlane();

        try
        {
            if (main != null)
            {
                handler.SetCurrentTransformationPlane(new TransformationPlane(main.GetCoordinateSystem()));
            }

            ArrayList secondaries = ass.GetSecondaries();
            foreach (ModelObject obj in secondaries)
            {
                Part part = obj as Part;
                if (part == null)
                {
                    continue;
                }

                count++;
                string signature = BuildSecondarySignature(part);
                int current;
                if (map.TryGetValue(signature, out current))
                {
                    map[signature] = current + 1;
                }
                else
                {
                    map.Add(signature, 1);
                }
            }
        }
        finally
        {
            handler.SetCurrentTransformationPlane(originalPlane);
        }

        return map;
    }

    private static string BuildSecondarySignature(Part part)
    {
        string profile = NormalizeKeyValue(GetReportProperty(part, "PROFILE"));
        string material = NormalizeKeyValue(GetReportProperty(part, "MATERIAL"));
        Box box = GetLocalBoundingBox(part);

        return string.Format("Perfil={0};Material={1};Box={2}", profile, material, FormatBox(box));
    }

    private struct Box
    {
        public Tekla.Structures.Geometry3d.Point Min;
        public Tekla.Structures.Geometry3d.Point Max;

        public Box(Tekla.Structures.Geometry3d.Point min, Tekla.Structures.Geometry3d.Point max)
        {
            Min = min;
            Max = max;
        }
    }

    private static Box GetLocalBoundingBox(Part part)
    {
        Solid solid = part.GetSolid();
        Tekla.Structures.Geometry3d.Point min = solid.MinimumPoint;
        Tekla.Structures.Geometry3d.Point max = solid.MaximumPoint;
        return new Box(min, max);
    }

    private static string FormatBox(Box box)
    {
        return string.Format(
            "Min({0},{1},{2}) Max({3},{4},{5})",
            FormatCoordinate(box.Min.X),
            FormatCoordinate(box.Min.Y),
            FormatCoordinate(box.Min.Z),
            FormatCoordinate(box.Max.X),
            FormatCoordinate(box.Max.Y),
            FormatCoordinate(box.Max.Z));
    }

    private static string FormatCoordinate(double value)
    {
        double rounded = RoundToTolerance(value);
        return string.Format("{0:F3}", rounded);
    }

    private static double RoundToTolerance(double value)
    {
        double tol = GeometryConstants.DISTANCE_EPSILON;
        if (tol <= 0.0)
        {
            tol = 0.001;
        }

        return Math.Round(value / tol) * tol;
    }

    private static List<string> BuildSecondaryDiffLines(Dictionary<string, int> map1, Dictionary<string, int> map2)
    {
        List<string> lines = new List<string>();
        SortedSet<string> keys = new SortedSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (string key in map1.Keys)
        {
            keys.Add(key);
        }
        foreach (string key in map2.Keys)
        {
            keys.Add(key);
        }

        foreach (string key in keys)
        {
            int count1 = map1.ContainsKey(key) ? map1[key] : 0;
            int count2 = map2.ContainsKey(key) ? map2[key] : 0;

            if (count1 > count2)
            {
                lines.Add(string.Format("[X] Secundaria faltando no conjunto 2: {0} (x{1})", key, count1 - count2));
            }
            else if (count2 > count1)
            {
                lines.Add(string.Format("[X] Secundaria extra no conjunto 2: {0} (x{1})", key, count2 - count1));
            }
        }

        return lines;
    }

    private static bool AppendStatusLine(StringBuilder sb, string label, bool ok)
    {
        if (!ok || IncludeOkDetails)
        {
            string mark = ok ? "[OK]" : "[X]";
            string status = ok ? "Iguais" : "Diferentes";
            sb.AppendLine(string.Format("{0} {1}: {2}", mark, label, status));
        }

        return ok;
    }

    private static string GetAssemblyNumberPrefix(Assembly ass)
    {
        if (ass == null || ass.AssemblyNumber == null)
        {
            return "-";
        }

        return Formatters.FormatValue(ass.AssemblyNumber.Prefix);
    }

    private static string GetAssemblyNumberStart(Assembly ass)
    {
        if (ass == null || ass.AssemblyNumber == null)
        {
            return "-";
        }

        return ass.AssemblyNumber.StartNumber.ToString();
    }

    private static string GetPartFinish(Part part)
    {
        if (part == null)
        {
            return "-";
        }

        return Formatters.FormatValue(part.Finish);
    }

    private static string GetPartName(Part part)
    {
        if (part == null)
        {
            return "-";
        }

        return Formatters.FormatValue(part.Name);
    }

    private static string GetPartClass(Part part)
    {
        if (part == null)
        {
            return "-";
        }

        return part.Class.ToString();
    }

    private static bool AppendCompareLine(StringBuilder sb, string label, string leftValue, string rightValue)
    {
        bool ok = AreEqualNormalized(leftValue, rightValue);
        if (!ok || IncludeOkDetails)
        {
            string mark = ok ? "[OK]" : "[X]";
            sb.AppendLine(string.Format("{0} {1}: {2} | {3}", mark, label, leftValue, rightValue));
        }

        return ok;
    }

    private static bool AppendCompareLine(StringBuilder sb, string label, int leftCount, int rightCount)
    {
        string leftText = FormatQuantity(leftCount);
        string rightText = FormatQuantity(rightCount);
        bool ok = leftCount == rightCount;
        if (!ok || IncludeOkDetails)
        {
            string mark = ok ? "[OK]" : "[X]";
            sb.AppendLine(string.Format("{0} {1}: {2} | {3}", mark, label, leftText, rightText));
        }

        return ok;
    }

    private static void AppendSectionSummary(StringBuilder sb, int okCount, int diffCount)
    {
        if (IncludeOkDetails)
        {
            return;
        }

        if (diffCount == 0 && okCount > 0)
        {
            sb.AppendLine(string.Format("[OK] Todos iguais ({0} linhas ocultas).", okCount));
            return;
        }

        if (okCount > 0)
        {
            sb.AppendLine(string.Format("[OK] Linhas iguais ocultas: {0}", okCount));
        }
    }

    private static string FormatQuantity(int count)
    {
        if (count == 1)
        {
            return "1 peca";
        }

        return string.Format("{0} pecas", count);
    }

    private static void AppendAssemblyPropertiesComparison(StringBuilder sb, Assembly ass1, Assembly ass2)
    {
        int okCount = 0;
        int diffCount = 0;

        if (AppendAssemblyPropertyLine(sb, ass1, ass2, "AREA")) okCount++; else diffCount++;
        if (AppendAssemblyPropertyLine(sb, ass1, ass2, "ASSEMBLY_PREFIX")) okCount++; else diffCount++;
        if (AppendAssemblyPropertyLine(sb, ass1, ass2, "WIDTH")) okCount++; else diffCount++;
        if (AppendAssemblyPropertyLine(sb, ass1, ass2, "HEIGHT")) okCount++; else diffCount++;
        if (AppendAssemblyPropertyLine(sb, ass1, ass2, "LENGHT")) okCount++; else diffCount++;
        if (AppendAssemblyPropertyLine(sb, ass1, ass2, "LENGHT_GROSS")) okCount++; else diffCount++;
        if (AppendAssemblyPropertyLine(sb, ass1, ass2, "MATERIAL_TYPE")) okCount++; else diffCount++;
        if (AppendAssemblyPropertyLine(sb, ass1, ass2, "VOLUME")) okCount++; else diffCount++;
        if (AppendAssemblyPropertyLine(sb, ass1, ass2, "WEIGHT")) okCount++; else diffCount++;
        if (AppendAssemblyPropertyLine(sb, ass1, ass2, "WEIGHT_GROSS")) okCount++; else diffCount++;
        if (AppendAssemblyPropertyLine(sb, ass1, ass2, "WEIGHT_NET")) okCount++; else diffCount++;

        AppendSectionSummary(sb, okCount, diffCount);
    }

    private static bool AppendAssemblyPropertyLine(StringBuilder sb, Assembly ass1, Assembly ass2, string propertyName)
    {
        string leftValue = GetAssemblyProperty(ass1, propertyName);
        string rightValue = GetAssemblyProperty(ass2, propertyName);
        return AppendCompareLine(sb, propertyName, leftValue, rightValue);
    }

    private static string GetAssemblyProperty(Assembly ass, string propertyName)
    {
        string value = GetReportProperty(ass, propertyName);
        if (value == "-")
        {
            if (string.Equals(propertyName, "LENGHT", StringComparison.OrdinalIgnoreCase))
            {
                value = GetReportProperty(ass, "LENGTH");
            }
            else if (string.Equals(propertyName, "LENGHT_GROSS", StringComparison.OrdinalIgnoreCase))
            {
                value = GetReportProperty(ass, "LENGTH_GROSS");
            }
        }

        return value;
    }

    private static string NormalizeKeyValue(string value)
    {
        if (string.IsNullOrWhiteSpace(value) || value == "-")
        {
            return "N/A";
        }

        return value.Trim().ToUpperInvariant().Replace(" ", "_");
    }

    private static bool AreEqualNormalized(string left, string right)
    {
        if (left == null)
        {
            left = string.Empty;
        }
        if (right == null)
        {
            right = string.Empty;
        }

        return string.Equals(left.Trim(), right.Trim(), StringComparison.OrdinalIgnoreCase);
    }

    private static string GetReportProperty(ModelObject obj, string propertyName)
    {
        if (obj == null)
        {
            return "-";
        }

        string stringValue = null;
        if (obj.GetReportProperty(propertyName, ref stringValue))
        {
            return Formatters.FormatValue(stringValue);
        }

        double doubleValue = 0.0;
        if (obj.GetReportProperty(propertyName, ref doubleValue))
        {
            return Formatters.FormatValue(string.Format("{0:F1}", doubleValue));
        }

        return "-";
    }
}

