param(
    [string]$SourceDir = (Join-Path $PSScriptRoot "..\\src"),
    [string]$OutputMacro = (Join-Path $PSScriptRoot "..\\macros\\MarnaTeklaOS.cs"),
    [string]$OutputTsep = (Join-Path $PSScriptRoot "..\\tsep\\RelatorioModelo\\Environments\\common\\macros\\modeling\\MarnaTeklaOS.cs"),
    [string]$OutputTekla = "C:\\TeklaStructures\\2023.0\\Environments\\common\\macros\\modeling\\MarnaTeklaOS.cs",
    [switch]$UpdateTekla
)

$ErrorActionPreference = "Stop"

$headerFile = Join-Path $SourceDir "00_Header.cs"
if (!(Test-Path $headerFile))
{
    throw "Arquivo de cabecalho nao encontrado: $headerFile"
}

$sourceFiles = Get-ChildItem -Path $SourceDir -Filter "*.cs" |
    Sort-Object Name |
    Where-Object { $_.Name -ne "00_Header.cs" }

$parts = New-Object System.Collections.Generic.List[string]
$parts.Add((Get-Content -Raw $headerFile))

foreach ($file in $sourceFiles)
{
    $parts.Add((Get-Content -Raw $file.FullName))
}

$generated = @"
// <auto-generated>
// Gerado por scripts\\build_macro.ps1 a partir de src\\*.cs. Nao edite diretamente.
// </auto-generated>

$($parts -join "`r`n`r`n")
"@

$generated = $generated -replace "`r?`n", "`r`n"

Set-Content -Path $OutputMacro -Value $generated -Encoding Ascii
Set-Content -Path $OutputTsep -Value $generated -Encoding Ascii

if ($UpdateTekla)
{
    $teklaDir = Split-Path $OutputTekla -Parent
    if (Test-Path $teklaDir)
    {
        Set-Content -Path $OutputTekla -Value $generated -Encoding Ascii
    }
    else
    {
        Write-Warning "Pasta do Tekla nao encontrada: $teklaDir"
    }
}
